name: Maven CI
on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16

    - uses: browser-actions/setup-chrome@latest
                          
    - name: Build with Maven
      run: mvn test --file UITests/pom.xml

    - uses: actions/upload-artifact@v2
      with:
        name: reports
        path: ./UITests/target
